### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by Noah-Huppert** [Noah-Huppert/squad-up#17]
When we first thought about this product we called it Squad Up because we called our group of friends a "Squad" and the saying "Squad Up" meant get together as a Squad. Which is exactly what this project is supposed to help do.

Unfortunately it looks like some other company scooped up the name and then proceeded to not do anything much. So we either need a new name or we need to check and see if the company SquadUp even exists anymore.

Once we think of a new name I can transfer ownership to a GH organization so its more even credit wise (I've only been managing the repo under my account until we think of a new name). Also we should rename everything in the app when we get a new name.

**Comment by Noah-Huppert** [comment]
General brainstorming guidelines would be:
- Try to make the name have anything to do with the product
- So avoid like Greek gods and stuff like that (Unless it sounds **really** cool)

**Comment by ROODAY** [comment]
Just brainstorming here:
* [Rago](http://www.urbandictionary.com/define.php?term=rago)
* Parlay/Parley
* GroupUp
* SquadPlans
* GroupPlans
* Congregate
* Shindig
* Crew
* Rally
* Flock
* Mass
* Swarm
* Powwow
* Jam Session
* Soiree
* Fete

**Comment by Noah-Huppert** [comment]
I like:
- Rago
- The idea of a name like Congregate
- Shindig has a special place in my heart
- Rally

**Comment by Noah-Huppert** [comment]
Looked at the Squad Up fb page and they are still posting actively :/

**Comment by ROODAY** [comment]
I think Rally has promise. Ideally it should be as short as possible IMO

**Comment by Noah-Huppert** [comment]
Working off Rally maybe Flock (The verb or noun). 

Also the idea of a big mass. Almost like a swarm. Also maybe space terminology for a big mass or something like Nebula.

**Comment by ROODAY** [comment]
I'm also down for something represents a big mass, i.e. flock or swarm, but idk about space words, it feels like that veers too far from the app's purpose

**Comment by Noah-Huppert** [comment]
Yea space words are nearing startup circle jerk territory

**Comment by Noah-Huppert** [comment]
Ok so we can't really do anything I think until we get a new name, I'm liking Rally or Flock (Although flock reminds me of Sheeple [sheep people])

**Comment by catvec** [comment]
Ok so "Flock" is the new name, let the ctrl-f'ing begin!
